twig:
    default_path: "%kernel.project_dir%/templates"
    # Pour appliquer Bootstrap dans le projet, pour le form theme d'inscription
    form_themes: ["bootstrap_5_layout.html.twig"]

when@test:
    twig:
        strict_variables: true
